In [7]:
import numpy as np

n = 10
A = np.diag([-2] * 10) + np.diag(3 * np.ones(n-4), -4) + np.diag(np.ones(n-2), 2)
print(f"A: {A}")

from scipy.linalg import lu, lu_factor, lu_solve
_lu, piv = lu_factor(A)
_, L, U = lu(A)

b = np.array([2*n - 2*i for i in range(0, n)])

xs = lu_solve((_lu, piv), b)
print(f"xs: {xs}")

r = A @ xs - b

from scipy.linalg import norm
r1norm = norm(r, ord=1)
print(f"r1norm: {r1norm}")

A: [[-2.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -2.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -2.  0.  1.  0.  0.  0.  0.]
 [ 3.  0.  0.  0. -2.  0.  1.  0.  0.  0.]
 [ 0.  3.  0.  0.  0. -2.  0.  1.  0.  0.]
 [ 0.  0.  3.  0.  0.  0. -2.  0.  1.  0.]
 [ 0.  0.  0.  3.  0.  0.  0. -2.  0.  1.]
 [ 0.  0.  0.  0.  3.  0.  0.  0. -2.  0.]
 [ 0.  0.  0.  0.  0.  3.  0.  0.  0. -2.]]
xs: [ 57.  49. 134. 116. 284. 246. 409. 355. 424. 368.]
r1norm: 2.1316282072803006e-13


In [9]:
def f(x):
    return (x-1)**3 + np.exp(x)
def g(x):
    return f(x) - 2
def secant_step(xn, xn1):
    return xn - (g(xn) * (xn - xn1)/(g(xn) - g(xn1)))

x0 = 3
x1 = 2.5
x2 = secant_step(x1, x0)
print(f"x2: {x2}")

tol = 2**(-52)
xn = x1
xn1 = x0
xe = xn
while True:
    xe = secant_step(xn, xn1)
    if (xe - xn) < tol:
        break
    xn1 = xn
    xn = xe

print(f"xe: {xe}")

x2: 1.958914133623982
xe: 1.958914133623982


In [19]:
def true_fn(x):
    return 1 + 2*x + 3*x**2 + 4*x**3 + 5*x**4

x = np.linspace(1, 10, 10)
y = true_fn(x)

from scipy.linalg import lstsq
M = np.column_stack((
    np.ones(len(x)),
    x,
    x**2,
    x**3,
    x**4
))
z,_,_,_ = lstsq(M, y)
preds = M @ z
lserr = norm(preds - y, ord=2)
print(f"lserr: {lserr}")

lserr: 4.1378723920282676e-11


In [25]:
f = lambda x : np.abs(np.cos(np.pi * x))

from scipy.integrate import quad
IQ = quad(f, 0, 2)
print(f"IQ: {IQ}")

NI = 1001
xI = np.linspace(0, 2, NI)
hI = 2/NI

wI = np.array([2] * NI)
wI[0] = wI[-1] = 1
fI = f(xI)

IT = hI/2 * (wI.T @ fI)
print(f"IT: {IT}")

print(f"No, the discontinuity at x=1 is not an issue because we do not differentiate anything")

IQ: (1.2732395447351628, 1.4210854715202004e-14)
IT: 1.2719633925496514
No, the discontinuity at x=1 is not an issue because we do not differentiate anything


In [ ]:
def f(x):
    return np.exp(x) * (x**2 + x**3)

N = 100
B = np.zeros((N-1, N-1))
b = np.zeros(N-1)

for n in range(1, N):
    a_n = n**2 + n
    b_n = 1 - n - 2*n**2
    c_n = n**2

    idx = n - 1
    B[idx][idx] = b_n
    if n > 1:
        B[idx][idx-1] = a_n
    if n < N-1:
        B[idx][idx+1] = c_n
    
    b[idx] = f(n/N)
    if n == N - 1:
        b[idx] -= c_n * np.exp(1)

from scipy.linalg import solve
U = solve(B, b)
print(U.shape)
true_f = lambda x : x * np.exp(x)
true_u = true_f(np.linspace(0, 1, N+1)[1:-1])

# true_u = [n/N * np.exp(n/N) for n in range(1, N)]
Uerr = norm(U - true_u, ord=2)
print(f"Uerr: {Uerr}")


(99,)
Uerr: 0.13533966963582736
