In [2]:
import numpy as np
from scipy.linalg import norm, lu, lu_factor, lu_factor
# Q1PA
n = 10
A = np.zeros((n, n))
for i in range(0, n):
    for j in range(0, n):
        A[i,j] = (j+i+1)/(j+i+1+1)
    A[i,i] = i

a = A[3][7]
b = A[4][4]
c = A[6][2]
print(f"a: {a}, b: {b}, c: {c}")

Acheck = norm(A.T @ A - np.eye(n), ord=2)
print(f"Acheck: {Acheck}")

comment1="No, because orthogonal <=> M^T M = I"

condA = np.linalg.cond(A)
print(f"condA: {condA}")

EigA, vec = np.linalg.eig(A)
EigA.sort()
EigA = EigA.reshape(1, -1)
print(f"EigA: {EigA}")

comment2 = 'no because one eigenvalue is negative'

n = 4
P,L,U = lu(A[0:4][0:4])
PM = P.T
print(PM)


a: 0.9166666666666666, b: 4.0, c: 0.9
Acheck: 183.32605835676466
condA: 32.596407004814566
EigA: [[-0.51714282  0.41650828  1.41176177  2.42628632  3.4500975   4.48131521
   5.52128313  6.57497945  7.65823786 13.57667332]]
[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]


In [5]:
def f(x):
    return (x-1)**4 + np.exp(x)
def g(x):
    return f(x) - 2
def g_prime(x):
    return 4*(x-1)**3 + np.exp(x)

def newton_step(x):
    return x - g(x)/g_prime(x)

x0 = 3
print(f"x0: {x0}")

x1 = newton_step(x0)
x2 = newton_step(x1)
x3 = newton_step(x2)
print(f"x1: {x1}, x2: {x2}, x3: {x3}")

tol = 2**(-52)
xe = x0
while True:
    xn = newton_step(xe)
    if (np.abs(xn - xe) < tol):
        break
    xe = xn
invf2 = xe
print(f"invf2: {invf2}")

x0: 3
x1: 2.3455853786540635, x2: 1.7650623277302933, x3: 1.2168575333869849
invf2: 0.6884238065328873


In [30]:
N = 6
h = 1/N
def f(x):
    return 3**x * (np.sin(np.pi*x))**2
all_x = np.linspace(0, 1, N+1)
w = np.ones(N+1) * 2
w[0] = w[-1] = 1
f = [f(x) for x in all_x]
print(all_x)
print(w)
print(f)
trapF = np.sum((w*0.5).T @ f) * h
print(trapF)

ws = 2*np.ones(N+1)
ws[0] = ws[N] = 1
ws[1::2] = 4
Qfs = h/3 * ws @ (np.array(f).T)
print(Qfs)

trsol = (4*((np.pi)**2))/(np.log(3)*((4*np.pi**2)+(np.log(3)**2)))
print(trsol)
errtrap = np.abs(trapF - trsol)
errsimp = np.abs(trsol - Qfs)
print(errtrap)
print(errsimp)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]
[1. 2. 2. 2. 2. 2. 1.]
[0.0, 0.30023423879400063, 1.0816871777305561, 1.7320508075688772, 1.5600628672889287, 0.624512383241704, 4.499279347985573e-32]
0.8830912457706779
0.883927211580961
0.8832365870682543
0.00014534129757637348
0.000690624512706739


In [49]:
tdat = np.linspace(1, 10, 10)
ydat = [106.236, 183.683, 139.279, 160.48, 207.895, 463.666, 388.06, 407.674, 442.674, 509.423]

from scipy.interpolate import CubicSpline
spl = CubicSpline(tdat, ydat)
teval = np.arange(1, 10) + 0.5
yspteval = spl(teval)
print(yspteval)
print("-------------")
from scipy.fft import fft
w = fft(ydat)
rw = w.real
print(rw)

m = 10
p = 5
a0 = w[0]/m

a = np.zeros(6)
for k in range(1, 5):
    a[k] = 2/m * rw[k]

a[5] = rw[5]/m

b = np.zeros(6)
for k in range(1, 5):
    b[k] = -2/m * w[k].imag

yteval = [a0 + np.sum([a[k] * np.cos(2*np.pi*k*t/m) + b[k] * np.sin(2*np.pi * k * t/m) for k in range(1,p+1)]) for t in teval]
print(a)
print(b)
print(yteval)

[177.92462938 158.97862062 148.01613814 159.71120182 347.58530458
 449.25295487 381.06125094 427.52979135 465.75545865]
-------------
[3009.07       -274.56906447   37.78764744 -398.61493553 -117.56764744
 -440.782      -117.56764744 -398.61493553   37.78764744 -274.56906447]
[  0.         -54.91381289   7.55752949 -79.72298711 -23.51352949
 -44.0782    ]
[   0.         -164.20095086  -34.29683426  -31.50323052   -6.42330217
    0.        ]
[(189.71887814385937+0j), (137.13822068352607+0j), (160.31721497066044+0j), (348.8817888433673+0j), (448.80066167413287+0j), (387.78459080476284+0j), (402.5336613673728+0j), (532.5570757042544+0j), (303.16458384397464+0j)]


In [ ]:
from scipy.linalg import solve
N = 4
h=1/N
x = np.linspace(0, 1, 5)
print(x)

A5 = np.diag([-2] * (N-1)) + np.diag(np.ones(N-2), 1) + np.diag(np.ones(N-2), -1) - 1/4**2 * np.diag(np.ones(N-1))
print(A5)

f5 = lambda x: -(np.pi**2 + 1)*np.sin(np.pi*x)-x

a = np.array([h**2*f5(x[1]), h**2*f5(x[2]), h**2*f5(x[3]) - 1])
print(a)
U4 = solve(A5, a)
print(U4)

[0.   0.25 0.5  0.75 1.  ]
[[-2.0625  1.      0.    ]
 [ 1.     -2.0625  1.    ]
 [ 0.      1.     -2.0625]]
[-0.49599819 -0.71060028 -1.52724819]
[0.9909891  1.54791684 1.4909891 ]


In [97]:
from scipy.linalg import solve, norm
def do5(N):
    h=1/N
    x = np.linspace(0, 1, N+1)

    A5 = np.diag([-2] * (N-1)) + np.diag(np.ones(N-2), 1) + np.diag(np.ones(N-2), -1) - h**2 * np.diag(np.ones(N-1))

    f5 = lambda x: -(np.pi**2 + 1)*np.sin(np.pi*x)-x

    a = np.array([h**2 * f5(xi) for xi in x[1:-1]])
    a[-1] = a[-1] - 1

    print(a.shape)
    print(A5.shape)
    U4 = solve(A5, a)
    return U4

U80 = do5(80)
U160 = do5(160)
U320 = do5(320)
def real_u(x):
    return np.sin(np.pi*x) + x
true_u = real_u(x)
E1 = norm(U80 - real_u(np.linspace(0, 1, 80+1)[1:-1]), np.inf)
E2 = norm(U160 - real_u(np.linspace(0, 1, 160+1)[1:-1]), np.inf)
E3 = norm(U320 - real_u(np.linspace(0, 1, 320+1)[1:-1]), np.inf)
print(f"{E1}, {E2}, {E3}")

(79,)
(79, 79)
(159,)
(159, 159)
(319,)
(319, 319)
0.0001166951712208153, 2.917236450450389e-05, 7.292998625452185e-06


In [100]:
OC1 = np.log(E1/E2)/np.log(2)
OC2 = np.log(E2/E3)/np.log(2)
print(OC1)
print(OC2)

2.0000706336949037
2.0000182982918147
