In [27]:
import sys
import numpy as np

## Question 1
### Basic Python arithmetic

In [12]:
# Part (A): Binary vs. Unary Operator
print(f"{-4**2}, {0 - 4**2}")

# (Explanation).
#   - Binary operators (i.e. exponentiation) have higher priority than unary operators (i.e. -x)
#       - so -4^2 gets interpreted as -(4^2).
#   - This means both become equivalent expressions.

-16, -16


In [16]:
# Part (B): Changing Sign
A = np.array([[1, 2], [3, 4]])
print(f"{A}, \n\n {-1 * A}, \n\n {-A}")

# (Explanation).
#   - In -1 * A, the unary operator is prioritised so it multiplies each element of A by -1
#       - this can be slow if A is large.
#   - On the other hand, -A just changes the sign of each element.

[[1 2]
 [3 4]], 

 [[-1 -2]
 [-3 -4]], 

 [[-1 -2]
 [-3 -4]]


In [17]:
# Part (C): Order of Evaluation
a, R, r = 2, 4, 2
print(f"{a/(R+r)}, {a/R+r}")

# (Explanation).
#   - LHS: using PEMDAS.
#   - RHS: just operating left-to-right.

0.3333333333333333, 2.5


In [20]:
# Part (D),(E): Rounding Error, Amplification of Rounding Error
print(0.75*0.2 - 0.15)
print(f"{np.floor(6/1)}, {np.floor(0.6/0.1)}")

# (Explanation).
#   - Should be 0, but is a really small number
#   - This occurs because many numbers cannot be represented exactly in binary, leading to tiny inaccuracies 
#       - this happens when the decimal terminates in base-10 but contains primes other than 2 in the denominator
#       - because we need scalar multiples of negative powers of 2, e.g. 3/8 = 3/(2*2*2) but not 1/10 = 1/(2*5)

2.7755575615628914e-17
6.0, 5.0


In [ ]:
# Part (F),(G): Catastrophic Cancellation
x, h1, h2 = 100, 1e-14, 1e-15
print(f"{x+h1-x}, {x-x+h1}, {x+h2-x}, {x-x+h2}")

# (Explanation). 
#   - x+h1 and x+h2 cause catastrophic cancellation because they're nearly equal
#       - so the error is exacerbated and the original h1 is lost.
#   - for x+h2-x, h2 is smaller than |x|*ε so x + h2 is stored as x and h2 is recoverable
#       - to see this, observe 1 + ε > 1 => x + xε > x.

1.4210854715202004e-14, 1e-14, 0.0, 1e-15


In [25]:
# Part (H),(I): Key Floating Point Parameters, Relative Machine Precision/Logicals
print(np.finfo(float).eps)      # ≈ 2.22e-16
print(np.finfo(float).tiny)     # Smallest positive normalized float ≈ 2.23e-308
print(np.finfo(float).max)      # Largest finite float ≈ 1.797e+308

eps = np.finfo(float).eps
print(1 + eps > 1)      # True      (as defined)
print(1 + eps/2 > 1)    # False     (as defined)

2.220446049250313e-16
2.2250738585072014e-308
1.7976931348623157e+308
True
False


## Questions 2-8
### Applications

In [ ]:
# Question (2): PI, Powers, Log, Exp and Equality

# (a) Solve π⁷ = eˣ => x = log(π⁷) = 7 * log(π)
x = 7 * np.log(np.pi)

# (b) Compute both sides
lhs = np.pi**7
rhs = np.exp(x)

# (c) Test equality
#   - returns False because of floating point rounding
#   - the error in storing x on a computer is roughly |x|ε
print(lhs == rhs)

# (d) Absolute error
print(abs(lhs - rhs))

# (e) Estimate rounding error for π⁷
lhs_single = np.float32(np.pi)**7
lhs_double = np.float64(np.pi)**7
print("Single precision:", lhs_single)
print("Double precision:", lhs_double)


False
1.3642420526593924e-12
Single precision: 3020.293816108053
Double precision: 3020.2932277767914


```python
# Question (3): IEEE Floating Point Extensions; Inf and NaN

# (a) Operations that lead to inf or nan
print(1/0)          # ➜ inf
print(-1/0)         # ➜ -inf
print(np.log(0))    # ➜ -inf
print(np.log(-1))   # ➜ nan

# (b) Working with zero and log
z = np.float64(0)
print(1/z)          # ➜ inf
print(-1/z)         # ➜ -inf
print(np.log(z))    # ➜ -inf

# (c) NaN-generating expressions
print(0/0)              # ➜ nan
print(z/z)              # ➜ nan
print(np.inf - np.inf)  # ➜ nan
print(0 * np.inf)       # ➜ nan
print(0 * np.nan)       # ➜ nan
print(np.exp(-np.inf))  # ➜ 0.0

# (Explanation). TL;DR:
#   - NaN:  math error or undefined
#   - Inf:  explosions or 'limits', e.g. 1/0 but not 0/0
```

In [ ]:
# Question (4): Multiples of π

# (a) Mathematically, sin(πk) = 0 for any integer k
# (b) Numerical evaluation
k = np.arange(0, 101)
f_k = np.sin(np.pi * k)

# Print a few to show if error is introduced
print(f_k[:10])     # should be very close to 0

# (Explanation).
#   - the errors occur because π has a storing error 

[ 0.00000000e+00  1.22464680e-16 -2.44929360e-16  3.67394040e-16
 -4.89858720e-16  6.12323400e-16 -7.34788079e-16  8.57252759e-16
 -9.79717439e-16  1.10218212e-15]


In [ ]:
# Question (5): Overflow and Underflow

# (a) Max t s.t. exp(t) is finite
max_log = np.log(np.finfo(float).max)
print("Max t for exp(t):", max_log)

# (b) Max t s.t. exp(-t) > 0: always true for all real t, but t -> inf leads to underflow
min_log = -np.log(np.finfo(float).tiny)
print("Max t for exp(-t) > 0:", min_log)

# (Explanation).
#   - the max_log will instantly overflow to infinity for any t greater.
#   - the min_log will experience gradual underflow because more non-normalised values smaller than realmin exist
#       - by forcing an implicit leading 1, we burn exponents forcing that 1 to the front.

Max t for exp(t): 709.782712893384
Max t for exp(-t) > 0: 708.3964185322641
Max x for exp(x^2): 26.641747557046326
Max x for exp(-x^2) > 0: 26.615717509251258


In [ ]:
# Question (6): Effect of Initial Condition on Recurrence

# (a) Use approximate value of e^(-1)
J_approx = np.empty(11)
J_approx[0] = 1 - 0.367879
for n in range(1, 11):
    J_approx[n] = 1 - n * J_approx[n-1]

print("Using approx exp(-1):", J_approx)

# (b) Use accurate exp(-1)
J_exact = np.empty(11)
J_exact[0] = 1 - np.exp(-1)
for n in range(1, 11):
    J_exact[n] = 1 - n * J_exact[n-1]

print("Using exp(-1):", J_exact)

# (Explanation).
# - The numbers appear unstable
#   - this is because the factor to the next term scales in n factorial
#   - so  even small inaccuracies will explode.

Using approx exp(-1): [ 0.632121  0.367879  0.264242  0.207274  0.170904  0.14548   0.12712
  0.11016   0.11872  -0.06848   1.6848  ]
Using exp(-1): [0.63212056 0.36787944 0.26424112 0.20727665 0.17089341 0.14553294
 0.12680236 0.1123835  0.10093197 0.09161229 0.08387707]


### Question (8): Time Estimation
Just use the formula: speed (flops/sec) = clock (cycles/sec or Hz) $\times$ cores $\times$ flops/cycle.

Note that the clock speed and flops/cycle are CPU-dependent.

### Question (9): Storage Questions
It's simple maths, just remember

- $x$-$n\text{B}$ = $x \times 2^{10n}$ bytes,

where $x$ is a number and $n$ is an order of magnitude corresponding to $1000^n$.

For example, 4MB = $4 \times 2^{2 \cdot 10}$ bytes.